name: Terraform Destroy

on:
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Destroy
        env:
          # Substitua 'TF_VAR_MY_VAR' por suas variáveis reais e adicione outras conforme necessário
          BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
        run: |
          terraform init
          terraform destroy -auto-approve