name: Terraform Destroy

on:
  workflow_dispatch: # Permite execução manual do workflow

env:
    # credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 bucket for the terraform state. 
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
    AWS_REGION: us-east-1
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Clean up
        run: rm -rf .terraform terraform.tfstate terraform.tfstate.backup
